title: napari-convpaint
author: Ana Stojiljkovic, Lucien Hinderling and Guillaume Witz 
logo: images/logo.png

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_extra_path: ['.','books/images']


