title: Convpaint
author: Roman Schwob, Lucien Hinderling, Ana Stojiljkovic and Guillaume Witz
logo: images/logo.png

execute:
  execute_notebooks: 'off'

sphinx:
  config:
    html_extra_path: ['.','books/images']
